### ISSUE TITLE
4A DOS w/Auto-start+CHARA1 companion GROM doesn't load GROM image

### ISSUE THREAD

**Issue by jedimatt42** [endlos99/finalgrom99#1]
Given a GROM file that has a header of:

0xAA00 0x0000 0x6010 0x0000
where 0x6010 is a powerup routine in the GROM.  and a ROM image with a standard ROM header... such as that of 4A DOS, with one or two program entries... 
FG99 does not create a menu entry for the GROM even though 4A's boot rom qualifies it as a valid GROM header with a powerup routine.  FG99 does create a menu entry for the ROM file... 

When loading the file from a menu entry, it looks like if it starts with a GROM, then it will load companion ROM files C and D, but if it starts with a ROM, it never looks for a companion G.BIN to load. 

I was able to work around this by adding a menu entry to my GROM so it would become the 'master' file for the entry. 

-M@

**Comment by endlos99** [comment]
Thanks for reporting this issue!

As you said, if no entries are found in the `G` file, the FinalGROM ignores this file entirely.  This holds true for any file.  But there's some logic that when an entry of a file that ends in `G` is selected, the files `G`, `C`, and `D` are loaded, if they exist.  If the entry is in a `C` file, then only `C` and `D` are loaded, since there is no `G` file in general. 

The solution to this problem would be to try to load a `G` file when selecting an entry in a `C` file.  This seems easy enough, but the problem is that for every "open" in the code, the microcontroller has to scan the entire directory for a file with the requested name.  This time is noticeable if the directory is near its limit of 171 entries -- I've tested it.

Now if this were a common pattern, I could still add the extra load as there would be a real benefit.  In this case, however, 4A DOS seems to be the only program known to be affected, and there is a known workaround.

So unless this problem rises again, I'll keep the current logic.
